DROP SEQUENCE IF EXISTS "hibernate_sequence";
DROP TABLE IF EXISTS "member";

CREATE SEQUENCE hibernate_sequence
  START WITH     1
  INCREMENT BY   1;

CREATE TABLE "member"(
  ID   INT                NOT NULL,
  NAME VARCHAR(25)       NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PHONE_NUMBER  VARCHAR(12) NOT NULL,
  PRIMARY KEY (ID)
);